# make sure the desktop has the icons we want, and nothing we don't
# also make sure we boot go GUI by default

---
# fix the icons on the desktop
- name: upload the lxde config file
  copy: src=files/lxde-panel-config dest=/home/yc/.config/lxpanel/LXDE-pi/panels/panel
        owner=yc group=yc
# setup the Xserver to auto start at boot and login yc
- name: Set the yc user to autologin on the GUI
  lineinfile: dest=/etc/lightdm/lightdm.conf state=present line=autologin-user=yc
              regexp=autologin-user=pi insertafter=EOF
- name: Set the GUI to start at boot time
  service: name=lightdm enabled=yes state=started
