# copy over the python_games directory and blow away the one that is there

---
- name: Make sure the golden python_games directory is on the box
  unarchive: dest=/opt/ src=files/python_games.tar.gz
- name: Set the owner and permissions so we can access the opt directory
  file: path=/opt/python_games recurse=yes mode=ugo+r
- name: Copy the python_games to the yc home directory
  unarchive: dest=/home/yc/ src=files/python_games.tar.gz
- name: Set the owner of python_games to yc
  file: path=/home/yc/python_games recurse=yes mode=ugo+r owner=yc group=yc
