# set the locale for the Pis

---
- name: make sure en locale package is enabled
  lineinfile: dest=/etc/locale.gen state=present line="en_US.UTF-8 UTF-8"
              regexp="# en_US.UTF-8 UTF-8"

- name: gen locale
  command: /usr/sbin/locale-gen {{ locale }}

- name: set locale
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}

- name: set localtime
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes

- name: set timezone
  template: src=templates/etc/timezone dest=/etc/timezone
  notify: update tzdata
