# initialize a brand new pi with the key necessary to work within the system
# run with the -k flag to enter the pi user's password:
# ansible-playbook -i hosts -k new_pi.yml

- name: Initialize a new Pi
  hosts: new
  remote_user: pi
  become: yes
  tasks:
      - include: tasks/root_key.yml
